### ISSUE TITLE
uniq 用法错误

### ISSUE THREAD

**Issue by Yansongsongsong** [guodongxiaren/LinuxTool#21]
https://github.com/guodongxiaren/LinuxTool/blob/master/%E8%BF%87%E6%BB%A4%E5%99%A8/README.md
里面
> -d
> uniq -d去除重复行。
> 同样要记得和sort联用。

这个描述有问题

‘-d’
‘--repeated’
Discard lines that are not repeated. When used by itself, this option causes uniq to print the first copy of each repeated line, and nothing else.

不是去除重复行啊。。 是去除不重复的行，留下重复的。这里重复的定义还是相邻的行

**Comment by Yansongsongsong** [comment]
### REF
https://www.gnu.org/software/coreutils/manual/coreutils.html#uniq-invocation

**Comment by guodongxiaren** [comment]
谢谢
